language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.3.0
os:
  - linux
install:
  - bundle install
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != false ]; then PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_pr; fi;'
